insert into narration values("AC","By Coolly  & Cartage ");
insert into narration values("AD","To Coffee      Coolly           Water   ");
insert into narration values("AP","To Coffee      Coolly       Poja");
insert into narration values("BB","By Bank Transfer");
insert into narration values("BD","By Discount ( )");
insert into narration values("BE","By Cartage");
insert into narration values("BN","By N. Commission");
insert into narration values("BS","By Sales");
insert into narration values("BT","By Transfer To Trading Account");
insert into narration values("C0","By Cheque No 5001");
insert into narration values("CA","By Coolly & Cartage");
insert into narration values("CB","By Cheque No 5645");
insert into narration values("CC","To C.Coolly");
insert into narration values("CE","To Cartage");
insert into narration values("CH","To  Cash");
insert into narration values("CO","By Co-oP B D.D No");
insert into narration values("CQ","By Cheque No.");
insert into narration values("CR","By Cash R.Charge");
insert into narration values("CS","By Closing Stock");
insert into narration values("CV","By S.B Cheque No 0805");
insert into narration values("CY","By  Coolly");
insert into narration values("DI","To Discount");
insert into narration values("DN","To Donation");
insert into narration values("IO","By I.O.B Cheque No ");
insert into narration values("NC","To N.Com");
insert into narration values("NF","To P 200623492");
insert into narration values("PJ","To Pooja");
insert into narration values("PL","To Profit & Loss Account");
insert into narration values("PN","By P.N.B Cheque No ");
insert into narration values("PP","To Petrol");
insert into narration values("SC","By  Cheque No 2214");
insert into narration values("SD","By Cheque No 0578");
insert into narration values("TC","To Coolly");
insert into narration values("TF","To Freight - Discount Received");
insert into narration values("TM","By  Cheque No 6428");
insert into narration values("TN","To N.Com");
insert into narration values("TO","To Opening Stock");
insert into narration values("TP","To Purchases");
insert into narration values("TR","Transfer  to  Trading  Account");
insert into narration values("VC","By C.B Cheque No 0222");
