insert into product (code,description) values ("IPAL","Profit And Loss Account");
insert into product (code,description) values ("PMDC","Purchase Account (Moong Dall Chip)");
insert into product (code,description) values ("FMDC","Freight Account (Moong Dall Chip)");
insert into product (code,description) values ("IMDC","Sales Account (Moong Dall Chip)");
insert into product (code,description) values ("PGDC","Purchase Account (Gram Dall Chip)");
insert into product (code,description) values ("FGDC","Freight Accont (Gram Dall Chip)");
insert into product (code,description) values ("IGDC","Sales Account (Gram Dall Chip)");
insert into product (code,description) values ("PTDC","Purchase  Account (Toor Dall Chip)");
insert into product (code,description) values ("FTDC","Freight Account (Toor Dall Chip)");
insert into product (code,description) values ("ITDC","Sales Account (Toor Dall Chip)");
insert into product (code,description) values ("PODC","Purchase Account (Orid Dall Chip)");
insert into product (code,description) values ("FODC","Freight Account (Orid Dall Chip)");
insert into product (code,description) values ("IODC","Sales Account (Orid Dall Chip)");
insert into product (code,description) values ("PWTC","Purchase Account (Wheat Chip)");
insert into product (code,description) values ("FWTC","Freight Account (Wheat Chip)");
insert into product (code,description) values ("IWTC","Sales Account (Wheat Chip)");
insert into product (code,description) values ("PAVC","Purchase Account (Avarai Chip)");
insert into product (code,description) values ("FAVC","Freight Account (Avarai Chip)");
insert into product (code,description) values ("IAVC","Sales Account (Avarai Chip)");
insert into product (code,description) values ("FKMC","Freight Account (Karamani Chip)");
insert into product (code,description) values ("PKMC","Purchase Account (Karamani Chip)");
insert into product (code,description) values ("IKMC","Sales Account (Karamani Chip)");
insert into product (code,description) values ("FWPC","Freight Account (W.Products)");
insert into product (code,description) values ("PWPC","Purchase Account (W.Products)");
insert into product (code,description) values ("IWPC","Sales Account (W.Products)");
insert into product (code,description) values ("FHGC","Freight Account (H.Gram Chip)");
insert into product (code,description) values ("PGMC","Purchase Account (Gram)");
insert into product (code,description) values ("FGMC","Freight Account (Gram)");
insert into product (code,description) values ("IGMC","Sales Account (Gram)");
insert into product (code,description) values ("PPPC","Purchase Account (P.Payaru)");
insert into product (code,description) values ("FPPC","Freight Account (P.Payaru)");
insert into product (code,description) values ("IPPC","Sales Account (P.Payaru)");
insert into product (code,description) values ("PCHI","Purchase Account (Chillies)");
insert into product (code,description) values ("ICHI","Sales Account (Chillies)");
insert into product (code,description) values ("FCHI","Freight Account (Chillies)");
insert into product (code,description) values ("PDHA","Purchase Account  (Dhania)");
insert into product (code,description) values ("IDHA","Sales Account (Dhania)");
insert into product (code,description) values ("FDHA","Freight Account (Dhania)");
insert into product (code,description) values ("PPEC","Purchase Account (Peas)");
insert into product (code,description) values ("FPEC","Freight Account (Peas)");
insert into product (code,description) values ("IPEC","Sales Account (Peas)");
insert into product (code,description) values ("PTUR","Purchase Account (Turmeric)");
insert into product (code,description) values ("FTUR","Freight Account (Turmeric)");
insert into product (code,description) values ("ITUR","Sales Account (Turmeric)");
insert into product (code,description) values ("PMTC","Purchase Account (Mustard)");
insert into product (code,description) values ("FMTC","Freight Account (Mustard)");
insert into product (code,description) values ("IMTC","Sales Account (Mustard)");
insert into product (code,description) values ("PMEC","Purchase Account (Menthi)");
insert into product (code,description) values ("IMEC","Sales Account (Menthi)");
insert into product (code,description) values ("FMEC","Freight Account (Menthi)");
insert into product (code,description) values ("PPDC","Purchase Account Peas Dall)");
insert into product (code,description) values ("FPDC","Freight Account (Peas Dall)");
insert into product (code,description) values ("IPDC","Sales Account (Peas Dall)");
insert into product (code,description) values ("ISEE","Sales Account (Seekkai)");
insert into product (code,description) values ("PMIL","Purchase Account (Millet)");
insert into product (code,description) values ("FMIL","Freight Account (Milllet)");
insert into product (code,description) values ("PSEE","Purchase Account (Seekkai)");
insert into product (code,description) values ("FSEE","Freight Account (Seekkai)");
insert into product (code,description) values ("PTAB","Purchase Account (Tamarind)");
insert into product (code,description) values ("FTAB","Freight Account (Tamarind)");
insert into product (code,description) values ("ITAB","Sales Account (Tamarind)");
insert into product (code,description) values ("PSUG","Purchase Account (Sugar)");
insert into product (code,description) values ("PGFC","Purchase Account (Gram Flour)");
insert into product (code,description) values ("ISUG","Sales Account (Sugar)");
insert into product (code,description) values ("IGFC","Sales Account (Gram Flour)");
insert into product (code,description) values ("IMIL","Sales Account (Millet)");
insert into product (code,description) values ("PJAC","Purchase Account (Jaggrey)");
insert into product (code,description) values ("FJAC","Freight Account (Jaggery)");
insert into product (code,description) values ("IJAC","Sales Account (Jaggery)");
insert into product (code,description) values ("PFLO","Purchase Account (Flour)");
insert into product (code,description) values ("IFLO","Sales Account (Flour)");
